spring:
  cloud:
    function:
      definition: process
    stream:
      kafka:
        streams:
          bindings:
            process-in-1:
              consumer:
                materialized-as: profanity_words_table
      bindings:
        process-in-0:
          destination: profanity_check
          contentType: application/json
        process-in-1:
          destination: profanity_words
          contentType: application/json
        process-out-0:
          destination: profanity_result
 #         contentType: application/json

  kafka:
    streams:
      application-id: fds