spring:
  cloud:
    function:
      definition: toLowerCase|echo
    stream:
      bindings:
        toLowerCase|echo-in-0:
          destination: test
#          contentType: application/json
        toLowerCase|echo-out-0:
          destination: ticket
 #         contentType: application/json

  kafka:
    streams:
      application-id: fds