spring:
  cloud:
    function:
      definition: toLowerCase
    stream:
      bindings:
        toLowerCase-in-0:
          destination: test
#          contentType: application/json
        toLowerCase-out-0:
          destination: ticket
 #         contentType: application/json

  kafka:
    streams:
      application-id: fds