spring:
  cloud:
    function:
      definition: toLowerCase|echo;toTable;process
    stream:
      kafka:
        streams:
          bindings:
            process-in-1:
              consumer:
                materialized-as: profanity_words_table
      bindings:
        toLowerCase|echo-in-0:
          destination: test
#          contentType: application/json
        toLowerCase|echo-out-0:
          destination: ticket
 #         contentType: application/json
#        toTable-in-0:
 #         destination: profanity_words
#          contentType: application/json
#        toTable-out-0:
#          destination: profanity_words
 #         contentType: application/json
        process-in-0:
          destination: profanity_check
          contentType: application/json
        process-in-1:
          destination: profanity_words
          contentType: application/json
        process-out-0:
          destination: profanity_result
 #         contentType: application/json

  kafka:
    streams:
      application-id: fds_2